server:
  port: 7002

spring:
  application:
    name: user-authority
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: user_authority
    url: jdbc:mysql://localhost:3306/online_taxi_user_authority?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
eureka:
  instance:
    hostname: user-authority.com
  client:
    service-url:
      defaultZone: http://eureka.com:7000/eureka

mybatis-plus:
  global-config:
    db-config:
      id-type: input