-- 权限表相关
CREATE TABLE AUTHORITY (
    ID VARCHAR(36) primary key,
    AUTHORITY_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    CREATE_TIME DATE NOT NULL,
    CREATOR_ID VARCHAR(36) NOT NULL,
    CREATOR_NAME VARCHAR(50) NOT NULL,
    UPDATE_TIME DATE NOT NULL,
    UPDATER_ID VARCHAR(36) NOT NULL,
    UPDATER_NAME VARCHAR(50) NOT NULL,
    IS_DELETED BIT NOT NULL
);

CREATE INDEX INDEX_AUTHORITY_NAME ON AUTHORITY(AUTHORITY_NAME);

-- 角色表相关
CREATE TABLE `ROLE` (
    ID VARCHAR(36) primary key,
    ROLE_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    CREATE_TIME DATE NOT NULL,
    CREATOR_ID VARCHAR(36) NOT NULL,
    CREATOR_NAME VARCHAR(50) NOT NULL,
    UPDATE_TIME DATE NOT NULL,
    UPDATER_ID VARCHAR(36) NOT NULL,
    UPDATER_NAME VARCHAR(50) NOT NULL,
    IS_DELETED BIT NOT NULL
);

CREATE INDEX INDEX_ROLE_NAME ON `ROLE`(ROLE_NAME);

CREATE TABLE `ROLE_AUTHORITY_RELATION` (
    ID VARCHAR(36) primary key,
    ROLE_ID VARCHAR(36) NOT NULL,
    AUTHORITY_ID VARCHAR(36) NOT NULL
);

